/**
 * The runs.
 *
 * What: Initial conditions. Same three laws, different members.
 * Why they are data: switching North Tower vs Rigid tree does not swap a
 * renderer. It flips `crush` (and a handful of impact numbers). If the
 * "video" theory were true, those two runs would be the same clip.
 *
 * PATH  = bonfire -> 1-story -> 2-story -> apartment  (things you have seen)
 * CLAIM = North, South, fire-stays-put, impact-only, rigid-tree
 */
import type { Scenario } from "./types.ts";

const WTC: Pick<
  Scenario,
  | "world"
  | "shape"
  | "floors"
  | "floorH"
  | "width"
  | "mass"
  | "viewScale"
  | "actionScale"
  | "defaultSpeed"
  | "hasPlane"
  | "clockStart"
  | "group"
  | "pathStep"
  | "nextId"
> = {
  world: "tower",
  shape: "tower",
  floors: 110,
  floorH: 3.66,
  width: 63.4,
  mass: 3.1e6,
  viewScale: 1.55,
  actionScale: 6.4,
  defaultSpeed: 150,
  hasPlane: true,
  clockStart: "08:46:30",
  group: "claim",
  pathStep: null,
  nextId: null,
};

export const SCENARIOS: Scenario[] = [
  {
    id: "bonfire",
    name: "Bonfire",
    short: "Pit · hash",
    blurb: "A log tower in a pit: || then =, like a hash. Each stick is four sections with three joins that hold until a neighbour is half charcoal, or the join hits ignition. One match. Fire walks. Logs blacken, then break. The crib does not shrink in place.",
    brief: "To Earn the Merit Badge, a Boy Scout must build a bonfire that can be lit with one match.",
    clockStart: "00:00:00",
    nistMinutes: 0,
    world: "pieces",
    shape: "bonfire",
    floors: 10,
    floorH: 0.15,
    width: 2.7,
    mass: 16,
    viewScale: 70,
    actionScale: 110,
    defaultSpeed: 8,
    hasPlane: false,
    group: "path",
    pathStep: 1,
    nextId: "house1",
    impactLo: 1,
    impactHi: 1,
    impactIntact: [1, 1, 1, 1, 1],
    fireSpread: 1,
    noFire: false,
    crush: true,
    hatTruss: false,
    planeAngle: 0,
    hasAntenna: false,
    heatRate: 5,
  },
  {
    id: "house1",
    name: "1-story house",
    short: "Tree, then couch",
    blurb: "A house you have seen. Dry Christmas tree, one match. The tree goes, then the couch, then the room. Timber chars. The roof comes down in the footprint — houses burn down, they do not roll over.",
    brief: "Dry Christmas tree, one match. Tree, then the couch, then the room. When the timber is charcoal, the roof drops in the footprint.",
    clockStart: "00:00:00",
    nistMinutes: 0,
    world: "pieces",
    shape: "house",
    floors: 1,
    floorH: 2.7,
    width: 8.2,
    mass: 140,
    viewScale: 26,
    actionScale: 52,
    defaultSpeed: 10,
    hasPlane: false,
    group: "path",
    pathStep: 2,
    nextId: "house2",
    impactLo: 1,
    impactHi: 1,
    impactIntact: [1, 1, 1, 1, 1],
    fireSpread: 1,
    noFire: false,
    crush: true,
    hatTruss: false,
    planeAngle: 0,
    hasAntenna: false,
    heatRate: 6,
  },
  {
    id: "house2",
    name: "2-story house",
    short: "Tree, then up",
    blurb: "The second floor is sitting on the first. Same tree, same gravity, more mass above. Fire walks up. Some internal timber goes. The roof lands on top. Pieces, not a chimney.",
    brief: "Same dry tree, one more story above it. Tree, then the couch, then up. Some timber internally. Roof lands on top.",
    clockStart: "00:00:00",
    nistMinutes: 0,
    world: "pieces",
    shape: "house",
    floors: 2,
    floorH: 2.7,
    width: 8.2,
    mass: 120,
    viewScale: 15,
    actionScale: 34,
    defaultSpeed: 10,
    hasPlane: false,
    group: "path",
    pathStep: 3,
    nextId: "apartment",
    impactLo: 1,
    impactHi: 1,
    impactIntact: [1, 1, 1, 1, 1],
    fireSpread: 1,
    noFire: false,
    crush: true,
    hatTruss: false,
    planeAngle: 0,
    hasAntenna: false,
    heatRate: 6,
  },
  {
    id: "apartment",
    name: "Apartment",
    short: "8 stories",
    blurb: "A brick stack now — walls, windows, a door, a parapet. Fire in one corner unit on the third story. Heat walks to the next room, then up. Extra height is extra mass, not a hinge. When a bay loses its columns the story pancakes into the one below.",
    brief: "A building, not a frame. One unit on the third story. Heat walks to the next room, then up.",
    clockStart: "00:00:00",
    nistMinutes: 0,
    world: "pieces",
    shape: "apartment",
    floors: 8,
    floorH: 3.05,
    width: 14,
    mass: 400,
    viewScale: 9.2,
    actionScale: 22,
    defaultSpeed: 8,
    hasPlane: false,
    group: "path",
    pathStep: 4,
    nextId: "north",
    impactLo: 3,
    impactHi: 4,
    impactIntact: [0.7, 0.85, 0.9, 1, 1],
    fireSpread: 1,
    noFire: false,
    crush: true,
    hatTruss: false,
    planeAngle: 0,
    hasAntenna: false,
    heatRate: 5,
  },
  {
    id: "north",
    name: "North Tower",
    short: "417 m · 110",
    blurb: "Same physics, 110 stories. More central hit, high in the stack. Fire spreads. The roof belt hangs the wound for a long time, then the upper block drops through the 63.4 m footprint.",
    brief: "Airplane hits, kerosene into the core. Fire starts on 93 and walks up, one story at a time, for 102 minutes. People die from paperwork, not kerosene.",
    ...WTC,
    nextId: "south",
    nistMinutes: 102,
    impactLo: 93,
    impactHi: 99,
    impactIntact: [0.28, 0.72, 0.62, 0.9, 0.94],
    fireSpread: 1,
    noFire: false,
    crush: true,
    hatTruss: true,
    planeAngle: 0,
    hasAntenna: true,
    heatRate: 1,
  },
  {
    id: "south",
    name: "South Tower",
    short: "77–85 · 56 min",
    blurb: "Corner hit, lower in the stack, more mass above. Visible lean, then the same crush. Historically the top section tilted before it came down.",
    brief: "Same thing.",
    ...WTC,
    clockStart: "09:03:02",
    nextId: "stays",
    nistMinutes: 56,
    impactLo: 77,
    impactHi: 85,
    impactIntact: [0.18, 0.42, 0.55, 0.82, 0.9],
    fireSpread: 1,
    noFire: false,
    crush: true,
    hatTruss: true,
    planeAngle: 0.12,
    hasAntenna: false,
    heatRate: 1.35,
    defaultSpeed: 150,
  },
  {
    id: "stays",
    name: "Fire stays put",
    short: "Doesn't spread",
    blurb: "Grant the claim: fire never leaves the impact belt and core. Opposite face stays cold. The damaged side still buckles first — watch whether Center Gravity actually leaves the 63 m base.",
    brief: "What happens if the fire stays put? Gravity is still enough.",
    ...WTC,
    nextId: "nofire",
    nistMinutes: 102,
    impactLo: 93,
    impactHi: 99,
    impactIntact: [0.28, 0.72, 0.62, 0.9, 0.94],
    fireSpread: 0,
    noFire: false,
    crush: true,
    hatTruss: true,
    planeAngle: 0,
    hasAntenna: true,
    heatRate: 1,
  },
  {
    id: "nofire",
    name: "Impact only",
    short: "No fire",
    blurb: "Same severed columns, no heating. Residual capacity on dead load is still >2×. This is why they stood for the better part of an hour — impact was not enough.",
    brief: "What happens if the plane wasn't fully loaded with fuel?",
    ...WTC,
    nextId: "tree",
    nistMinutes: 102,
    impactLo: 93,
    impactHi: 99,
    impactIntact: [0.28, 0.72, 0.62, 0.9, 0.94],
    fireSpread: 0,
    noFire: true,
    crush: true,
    hatTruss: true,
    planeAngle: 0,
    hasAntenna: true,
    heatRate: 1,
  },
  {
    id: "tree",
    name: "Rigid tree",
    short: "No crush",
    blurb: "Same gravity and fire, but floors are not allowed to fail. The upper block is a chimney on a hinge. This is the cartoon that produces a tip-over. Buildings are not chimneys.",
    brief: "What if the tower was a giant tree?",
    ...WTC,
    nistMinutes: 102,
    impactLo: 93,
    impactHi: 99,
    impactIntact: [0.22, 0.55, 0.5, 0.85, 0.92],
    fireSpread: 1,
    noFire: false,
    crush: false,
    hatTruss: true,
    planeAngle: 0,
    hasAntenna: true,
    heatRate: 1.15,
  },
];

export const PATH = SCENARIOS.filter((s) => s.group === "path");
export const CLAIM = SCENARIOS.filter((s) => s.group === "claim");

export function scenarioById(id: string): Scenario {
  return SCENARIOS.find((s) => s.id === id) ?? SCENARIOS[0];
}
